### ISSUE TITLE
Problem getting authenticated on php lang

### ISSUE THREAD

**Issue by cod3gen** [nicehash/rest-clients-demo#1]
Hi!

I'm having problems getting proper signed requests on php language, keep ending up with invalid session error.  Possible to get some examples for PHP up?

**Comment by cod3gen** [comment]
Literally solved signing 5 seconds after pushing this issue... Would still be great to have demo for PHP though

**Comment by undert03** [comment]
@cod3gen getting the exact same issue with my php curl request. feel like posting some sample php code?

**Comment by undert03** [comment]
Always get "errors":[{"code":2000,"message":"Invalid Session"}]

I am guessing I did not set up my sign data properly.
My OrgID matches what's in my account and the API info is set up under my Org.


**PHP CODE**
```
define('NH_API_KEY', 'XXXX' );
define('NH_API_SEC', 'XXXX' );
define('NH_ORGID',    'da41b3bc-3d0b-4226-b7ea-aee73f94a518' );
$UTCtime 		= UTC_Get_Millis();
$OrgID 			= NH_ORGID;
$Nonce			= GEN_UUIDv4();
$Method   	= 'GET';
$Path				= "/main/api/v2/mining/info";
$Query			= "";
$SigData 		= NH_API_KEY."\x00{$UTCtime}\x00{$Nonce}\x00\x00{$OrgID}\x00\x00{$Method}\x00{$Path}\x00{$Query}";
$Signature 	= hash_hmac('sha256', $SigData, NH_API_SEC );

$RequestID = GEN_UUIDv4();

$Headers = array(
	"X-Time: {$UTCtime}",
	"X-Nonce: {$Nonce}",
	"X-Organization-Id: {$OrgID}",
	"X-Request-Id: {$RequestID}",
	"X-Auth: ".NH_API_KEY.":{$Signature}",
);
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, "https://api2.nicehash.com{$Path}/" );
curl_setopt($curl, CURLOPT_HTTPHEADER, $Headers );
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($curl);
if(!$result){
	die("Connection Failure");
}
curl_close($curl);
echo $result;
```

**Comment by cod3gen** [comment]
Hi undert03!

This was my solution;
`public static function getAuthHeader($time = null, $nonce = null, $request = array(), $orginaizationId = null, $apiKey = null, $apiSecret = null) {
		if ($apiKey === null) $apiKey = Util::arraySafeVal(Yii::$app->params, "NICEHASH_NKEY");
		if ($apiSecret === null) $apiSecret = Util::arraySafeVal(Yii::$app->params, "NICEHASH_SECRET");
		if ($orginaizationId === null) $orginaizationId = Util::arraySafeVal(Yii::$app->params, "NICEHASH_ORGID");
		if (!$apiKey || !$apiSecret) return false;
		
		$hmac = hash_init('sha256', HASH_HMAC, $apiSecret);
		hash_update($hmac, $apiKey);
		hash_update($hmac, "\0");
		hash_update($hmac, $time);
		hash_update($hmac, "\0");
		hash_update($hmac, $nonce);
		hash_update($hmac, "\0");
		hash_update($hmac, "\0");
		hash_update($hmac, $orginaizationId);
		hash_update($hmac, "\0");
		hash_update($hmac, "\0");
		hash_update($hmac, $request['method']);
		hash_update($hmac, "\0");
		hash_update($hmac, $request['path']);
		hash_update($hmac, "\0");
		if (isset($request['query'])) hash_update($hmac, http_build_query($request['query']));
		if (isset($request['body'])) {
			hash_update($hmac, "\0");
			hash_update($hmac, $request['body']);
		} 
		return $apiKey.':'.hash_final($hmac);
		
	}
	
	public static function QueryNicehash2($path, $api = 'public', $params = array(), $type = 'main', $method = 'GET', $apiKey = null, $apiSecret = null, $raw = false) {
		if (!$path) return false;
		
		$status       = null;
		$error        = null;
		$raw_response = null;
		$response     = null;
		$headers	  = null;
		
		if ($type)
			$path= "/{$type}/api/v2/{$path}";
		else $path = "/api/v2/{$path}";

		$request = array('method' => $method, 'path' => $path);
		if (!empty($params) && is_array($params) && $method !== 'GET')
			$request['body'] = json_encode($params);
		elseif (!empty($params) && is_array($params)) {
			$request['query'] = $params;
		}
		
		
		if ($api !== 'public') {
			$xnonce = Util::generateRandomString(32);
			$xtime = Util::milliseconds();
			$xorginaizationId = Util::arraySafeVal(Yii::$app->params, "NICEHASH_ORGID");
			$headers = array(
				'X-Request-Id' => $xnonce,
				'X-User-Agent' => 'PowerminingPool',
				'X-Time' => $xtime,
				'X-Nonce' => $xnonce,
				'X-Organization-Id' => $xorginaizationId,
				'X-Auth' => self::getAuthHeader($xtime, $xnonce, $request, $xorginaizationId, $apiKey, $apiSecret),
			);
		}
		
		if (!$headers) {
            $headers = array();
        } elseif (is_array($headers)) {
            $tmp = $headers;
            $headers = array();
            foreach ($tmp as $key => $value) {
                $headers[] = $key . ': ' . $value;
            }
        }
		
		$headers[] = 'Content-Type: application/json; charset=utf-8';
		$url = "https://api2.nicehash.com".$path;
		if ($method === 'GET' && isset($request['query'])) $url .= '?'.http_build_query($request['query']);
		$curl    = curl_init($url);
		$options = array(
			CURLOPT_CONNECTTIMEOUT => 5,
			CURLOPT_TIMEOUT        => 10,
			CURLOPT_RETURNTRANSFER => TRUE,
			CURLOPT_FOLLOWLOCATION => TRUE,
			CURLOPT_MAXREDIRS      => 3,
		);
		curl_setopt_array($curl, $options);
		if ($headers) {
            curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        }
		if ($method === 'GET')
			curl_setopt($curl, CURLOPT_HTTPGET, true);
        elseif ($method === 'POST') {
			curl_setopt($curl, CURLOPT_POST, true);
			if (isset($request['body']))
				curl_setopt($curl, CURLOPT_POSTFIELDS, $request['body']);
		} elseif ($method == 'PUT') {
            curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
            if (isset($request['body'])) curl_setopt($curl, CURLOPT_POSTFIELDS, $request['body']);
            $headers[] = 'X-HTTP-Method-Override: PUT';
        } elseif ($method == 'PATCH') {
            curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PATCH');
            if (isset($request['body'])) curl_setopt($curl, CURLOPT_POSTFIELDS, $request['body']);
        } elseif ($method === 'DELETE') {
            curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'DELETE');
            if (isset($request['body'])) curl_setopt($curl, CURLOPT_POSTFIELDS, $request['body']);
		}
		Util::throttle(1000);
		$raw_response	= curl_exec($curl);
		Util::throttleSetNewTime();
		$response   	= json_decode($raw_response, TRUE);
		$status 		= curl_getinfo($curl, CURLINFO_HTTP_CODE);
		$curl_error 	= curl_error($curl);
		$curl_errno 	= curl_errno($curl);
		curl_close($curl);
		
		if (!empty($curl_error)) {
			$error = $curl_error;
		}
		
		$result = array();
		
		if (isset($response['error_id'])) {
			$result['success'] = false;
			$result['error']['id'] = $response['error_id'];
			$result['error']['errors'] = $response['errors'];
		} else {
			$result['error'] = null;
			$result['success'] = true;
		}

		if ($status != 200) {
			// If bitcoind didn't return a nice error message, we need to make our own
			switch ($status) {
				case 400:
					$error = 'HTTP_BAD_REQUEST';
					break;
				case 401:
					$error = 'HTTP_UNAUTHORIZED';
					break;
				case 403:
					$error = 'HTTP_FORBIDDEN';
					break;
				case 404:
					$error = 'HTTP_NOT_FOUND';
					break;
			}
			$result['success'] = false;
			$result['error']['statusCode'] = $status;
		}
		
		if ($result['success'] === true) $result['result'] = $response;
		else $result['result'] = null;

		if ($raw) return $raw_response;
		return $result;
	}`
