### ISSUE TITLE
API key generation doesn't work

### ISSUE THREAD

**Issue by mr-older** [nicehash/rest-clients-demo#11]
Since Nicehash on new platform closed all addresses to get help (just no information, how to get help), I have to write here: creation of ne API keys doesn't work (FF 68.01, Chrome 77.038, ... )

I've got `API key creation failed`, that's all. Fresh new account on new version of platform, tried different accounts.

So your rest API doesn't work too :)

**Comment by bl4z** [comment]
if your password was reset or 2FA disabled there is 7 day moratorium on creating API key ... (since one can withdraw money with this key) ... please contact support for more details
