### ISSUE TITLE
Java example with time rage

### ISSUE THREAD

**Issue by pawelantczak** [nicehash/rest-clients-demo#12]
Hello.
I'm not able to figure out how to make Java example to work with URL:
```https://api2.nicehash.com/main/api/v2/mining/rigs/stats/algo/```
Do you have any example of call with time rage?

**Comment by xrado** [comment]
Hi,

query params:
```
algorithm number | algorithm for stats (order from algos list)
afterTimestamp number | after timestamp (inclusive, default: now - 7 days)
beforeTimestamp number | before timestamp (exclusive, default: now)
```

example ```main/api/v2/mining/rigs/stats/algo?afterTimestamp=1571731230715&algorithm=20```

algorithm 20 is for DAGGERHASHIMOTO
afterTimestamp = now - 1 day  (for the last day of stats)
If you want for specific range add beforeTimestamp which defines end of range

best
