### ISSUE TITLE
nicehash.py wrong path to the endpoint

### ISSUE THREAD

**Issue by frstrtr** [nicehash/rest-clients-demo#14]
nicehash.py
(https://github.com/nicehash/rest-clients-demo/blob/865e14981ef04fabedf21fb7c84bcd828d9a9cfd/python/nicehash.py#L61)

    def get_curencies(self):
        return self.request('GET', '/api/v2/enum/currencies/', '', None)

Exception: 404: Not Found

get_curencies method missed second 'r' in 'curencies' by design? 

this also leads to 

(https://github.com/nicehash/rest-clients-demo/blob/865e14981ef04fabedf21fb7c84bcd828d9a9cfd/python/test_bot.py#L76)
  my_btc_account = private_api.get_accounts_for_currency(currencies['currencies'][0]['currency'])

generate
  
NameError: name 'currencies' is not defined

**Comment by bl4z** [comment]
sorry .. this is new URL -- we will fix sample

https://api2.nicehash.com/main/api/v2/public/currencies

**Comment by frstrtr** [comment]
You have to fix API docs then too...
