### ISSUE TITLE
Malformed request

### ISSUE THREAD

**Issue by faneaatiku** [nicehash/rest-clients-demo#18]
Hello, 

I'm getting the following error: 
`,"errors":[{"code":60,"message":"Malformed request"}]`
When I'm trying to call "/main/api/v2/hashpower/myOrders/" on the production environment. 

I'm using the examples from this repo with this exact file : https://github.com/nicehash/rest-clients-demo/blob/master/javascript/api.js

apiKey, apiSecret and organisation id are 100% correct. I checked them several times. 

What this error might mean ? 
Thanks

**Comment by bl4z** [comment]
malformed request means that something is wrong with input params (not headers)
but if u send error_id we can see exactly whats wrong .... pleas send as support ticket (and mention in ticket this issue id)

**Comment by faneaatiku** [comment]
Can't we(all software devs using the APIs) get the meaning of the error codes ?

**Comment by bl4z** [comment]
usually codes are self explanatory for ie...
```	ORDER_EXPIRED(5058, "Order already expired", HttpStatus.BAD_REQUEST),
	ORDER_NOT_ACTIVE(5059, "Order not active", HttpStatus.BAD_REQUEST),
	ORDER_PRICE_TOO_LOW(5060, "Order price too low", HttpStatus.BAD_REQUEST),
	ORDER_PRICE_CANNOT_BE_DECREASED_YET(5061, "Order price cannot be decreased yet, allowed once per 10 minutes. Seconds till available:  %s", HttpStatus.BAD_REQUEST),```

bun in case of malformed request; request is droped by framework when param types doesnt match .. and wont help a lot

**Comment by faneaatiku** [comment]
I see. Thanks for answering.
