### ISSUE TITLE
c# client got an exception {"Unexpected JSON token when reading DataTable. Expected StartArray, got StartObject. Path '', line 1, position 1."}

### ISSUE THREAD

**Issue by noobookbig** [nicehash/rest-clients-demo#19]
After deprecate API has been added/change the c# client got an exception

{"Unexpected JSON token when reading DataTable. Expected StartArray, got StartObject. Path '', line 1, position 1."}

![image](https://user-images.githubusercontent.com/12130745/79716472-f6148500-8300-11ea-8a3f-64bddf52b799.png)

**Comment by bl4z** [comment]
fixed
