### ISSUE TITLE
Lazarus client, Indy package for HTTP requests

### ISSUE THREAD

**Issue by xelaxin** [nicehash/rest-clients-demo#22]
I'm constantly receiving error 2000
{"error_id":"42b8c1a3-5911-499f-8dd6-5835d0f26163","errors":[{"code":2000,"message":"Invalid session"}]}

I did examples for sign that i found here, my hash is 100% ok, for both situations GET and PUT. I'd added all needed Headers, but, i'm still stuck with that error. 
And, requests get 401 error when i'm not add username and password, When i add login credential connection is established but error 2000 appears. I did not found nothing in api docs about login and password neither your examples have. What i'm doing wrong, pls give me a hand!
Thank you!

**Comment by bl4z** [comment]
hi ... can u please write down sample request with all required params .. so we can try to find problem .. 
however if u look api docs or examples u should see how headers are generated and what header are needed
https://docs.nicehash.com/ look under _Signing requests_
