### ISSUE TITLE
Getting error code 10 on withdrawl

### ISSUE THREAD

**Issue by encloinc** [nicehash/rest-clients-demo#35]
Withdrawl endpoint seems to be broken, somehow? Atfirst started getting "unsupported media type" and as soon as I added the  accept & contenttype headers for a json request im now getting:

{
  error_id: '8b31ab1d-351e-4cbe-a60d-cc872de5af85',
  errors: [
    {
      code: 10,
      message: 'An error occurred while fulfilling the request'
    }
  ]
}

**Comment by encloinc** [comment]
Seems to specifically be this header that triggers the error:
options['headers']['Content-Type'] = "application/json;charset=UTF-8";

**Comment by bl4z** [comment]
[withdrawalAddressId must not be null] 

for mentioned error message
