### ISSUE TITLE
body for POST request malformed

### ISSUE THREAD

**Issue by jbrepogmailcom** [nicehash/rest-clients-demo#42]
Hello, following command line is not working, probably because the body parameter with POST request is not properly formatted, but according to documentation it should work. GET requests work, but not POST:

`
nicehash -b https://api2.nicehash.com -o key -k key -s secret -m POST -p "/main/api/v2/hashpower/order/some_order/updatePriceAndLimit" -d {\"price\":0.0050,\"limit\":0.9,\"displayMarketFactor\":\"GH\",\"marketFactor\":1000000000}
`

**Comment by bl4z** [comment]
it should be POST ... [updatePriceAndLimit](https://www.nicehash.com/docs/rest/post-main-api-v2-hashpower-order-id-updatePriceAndLimit) // what is the err message

**Comment by jbrepogmailcom** [comment]
eval python3 ./nicehash.py -b https://api2.nicehash.com -o organization -k key -s secret -m POST -p "/main/api/v2/hashpower/order/b5fb1be5-e812-4dab-a87b-f6500cd36e35/updatePriceAndLimit" -d {"price":0.0059,"limit":0.9}
Unexpected error: 400: Bad Request: b'{"error_id":"e336d35f-d6d2-4e83-82f3-0243460d0310","errors":[{"code":60,"message":"Malformed request"}]}'

**Comment by bl4z** [comment]
hi

just send all 4 attributes IE {"marketFactor":"1000000000000.00000000","displayMarketFactor":"TH","limit":"0.00100000","price":"0.12"}
first two algos prevent accidential price update in case something chnages on market .. and can be obtained in https://api2.nicehash.com/main/api/v2/mining/algorithms

**Comment by jbrepogmailcom** [comment]
Sorry I have already tried that before and it is not working either.
`
eval python3 ./nicehash.py -b https://api2.nicehash.com -o org -k key -s sec -m POST -p "/main/api/v2/hashpower/order/b5fb1be5-e812-4dab-a87b-f6500cd36e35/updatePriceAndLimit" -d {"marketFactor":"1000000000000000.00000000","displayMarketFactor":"PH","limit":"0.100000","price":"0.0054"}
Unexpected error: 400: Bad Request: b'{"error_id":"cc7d723e-adf7-4aa4-b8ca-f544fb8bc272","errors":[{"code":60,"message":"Malformed request"}]}'
'

**Comment by bl4z** [comment]
there must be something with quotes send to api ..

`No String-argument constructor/factory method to deserialize from String value ('marketFactor:1000000000000000.00000000');  `

**Comment by jbrepogmailcom** [comment]
Sorry, not working. How would you then format "displayMarketFactor:PH" ? This did not work either: "displayMarketFactor:\"PH\""

**Comment by bl4z** [comment]
hi 

there seems to be issue with json.dumps function ...
try to make this correction into nicehash.py in line 110
`body_json = body #json.dumps(body)`

then it should work ...

python3 nicehash.py -b https://api-test-dev.nicehash.com -o xxx -k xxx -s xxx -m POST -p /main/api/v2/hashpower/order/786a59d3-d7df-4f74-a8ce-ab0c5296a828/updatePriceAndLimit -d "{\"marketFactor\":\"1000000000000.00000000\",\"displayMarketFactor\":\"TH\",\"limit\":\"0.00100000\",\"price\":\"0.14\"}"

{'id': '786a59d3-d7df-4f74-a8ce-ab0c5296a828', 'createdTs': '2021-11-15T11:11:25.855303Z', 'updatedTs': '2021-11-15T11:11:25.855303Z', 'requestId': '9bryufybbn6mbs08xpfwna581cnfe41z', 'type': {'code': 'STANDARD', 'description': 'Standard'}, 'market': 'EU', 'algorithm': {'algorithm': 'DAGGERHASHIMOTO', 'title': 'DaggerHashimoto', 'enabled': True, 'order': 20}, 'status': {'code': 'ACTIVE', 'description': 'Active'}, 'price': '0.14000000', 'limit': '0.00100000', 'amount': '0.00100000', 'availableAmount': '0.00096030', 'payedAmount': '0.00000000', 'alive': True, 'startTs': '2021-11-15T11:11:25.615715Z', 'endTs': '2021-11-25T11:11:25.615715Z', 'pool': {'id': '0762f3fd-8efb-451d-855c-5b834472dfb7', 'name': 'test', 'algorithm': 'DAGGERHASHIMOTO', 'stratumHostname': '10.10.0.72', 'stratumPort': 16020, 'username': 'x', 'password': 'x', 'inMoratorium': False}, 'organizationId': '9e376d1e-b83c-42cb-80df-6bb5b20b9942', 'creatorUserId': '435281a9-7d96-4fc1-a2e5-f7b17cac541d', 'rigsCount': 0, 'acceptedCurrentSpeed': '0.00000000', 'displayMarketFactor': 'TH', 'marketFactor': '1000000000000.00000000', 'estimateDurationInSeconds': 0, 'liquidation': 'OPEN', 'meta': '{"geoInfo":{"country":"SI","src":"KYC"}}'}
