### ISSUE TITLE
Invalid Session - WITHDRAWAL

### ISSUE THREAD

**Issue by vreaw** [nicehash/rest-clients-demo#44]
when I try to withdraw with the api 
`curl /main/api/v2/accounting/withdrawal2/{currency}/{id}`

i have the following answer:
`{"error_id":"87e68fc4-b67d-468e-b570-ddae003ba9db","errors":[{"code":2000,"message":"Invalid session"}]}`

is this because i have 2FA enabled? if yes is there any way to request with the 2fa code?

**Comment by bl4z** [comment]
Hi

2FA is needed when adding WD addr not for actual WD // something is wrong with auth headers or api key
