### ISSUE TITLE
[RPC][propose] get back count to next allowed price move-down

### ISSUE THREAD

**Issue by Ur-Quan** [nicehash/rest-clients-demo#5]
Hi.
Old nh rpc error message has a countdown:
`"Price decrease possible after seconds: XXX"`

New one doesn't have it. Please get it back like:
`{"error_id":"bla","errors":[{"code":5061,"message":"Order price cannot be decreased yet, allowed once per 10 minutes","Price decrease possible after seconds":"XXX"}]}`

**Comment by bl4z** [comment]
for now u can use this attribute:
[updatedTs] => 2019-03-16T08:17:15.015Z
but i think your proposal makes sense ...

**Comment by bl4z** [comment]
this has now been added
