### ISSUE TITLE
NHOS POST Malformed request 60 with /main/api/v2/mining/rigs/status2

### ISSUE THREAD

**Issue by liamcole45** [nicehash/rest-clients-demo#61]
Hi, GET API examples work fine, keep getting a malformed request with POST. Is anyone able to tell me what this error code is related too?

`python3 nicehash.py -b https://api2.nicehash.com -o orgid -k key -s secret -m POST -p /main/api/v2/mining/rigs/status2 -d '{"rigId": "rigidhere", "deviceId": "2-4", "action": "STOP"}'`

`Unexpected error: 400: Bad Request: b'{"error_id":"b8220586-b6b5-4cf6-a793-aaf8fde97432","errors":[{"code":60,"message":"Malformed request"}]}'`

My rig is running NHOS

**Comment by Guccisxinesstrading** [comment]
Please can someone help me in doing that

**Comment by bl4z** [comment]
the easies way by far would be to make test request with help of docs ..
https://www.nicehash.com/docs/rest/-miner-private // login to NH and use .. _Fill logged-in user credentials_
from there u can test api call and see params and responses 

![Screenshot 2023-10-24 at 08 46 21](https://github.com/nicehash/rest-clients-demo/assets/1046938/56e00695-18c9-4e63-8354-d8640cba60ce)
