### ISSUE TITLE
Working PHP API Code?

### ISSUE THREAD

**Issue by huseyinergen** [nicehash/rest-clients-demo#68]
Hello everyone. I have tested all codes here. But I don't get any good working code. Can anybody share with us the working PHP code here?
Best programming to everybody
Note: I want only to get balance and mining information (estimated daily rewards etc.)

**Comment by huseyinergen** [comment]
There is no response

**Comment by bl4z** [comment]
look here

https://github.com/nicehash/rest-clients-demo/wiki
