### ISSUE TITLE
Income Projections

### ISSUE THREAD

**Issue by jawiv** [nicehash/rest-clients-demo#9]
I've been looking through the API documentation and I can find no reference to income projections (a feature of the old api).

On the NiceHash website, it is easy to find the income projections (https://www.nicehash.com/my/mining/stats).

Is this functionality available in the v2 API? If not, will it be in the future? I found this information very useful in the v1 API.

**Comment by bl4z** [comment]
in main/api/v2/mining/rigs you have profitability: 0.0006912000000000001 (per worker)
